version: "3.9"

services:
  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password_123
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password_123
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order_pg_data:/var/lib/postgresql/data

  catalog-postgres:
    image: postgres:16
    container_name: catalog-postgres
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password_123
      POSTGRES_DB: catalog_db
    ports:
      - "5434:5432"
    volumes:
      - catalog_pg_data:/var/lib/postgresql/data

  customer-postgres:
    image: postgres:16
    container_name: customer-postgres
    environment:
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_password_123
      POSTGRES_DB: customer_db
    ports:
      - "5436:5432"
    volumes:
      - customer_pg_data:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password_123
      POSTGRES_DB: payment_db
    ports:
      - "5437:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  auth_pg_data:
  order_pg_data:
  catalog_pg_data:
  customer_pg_data:
  payment_pg_data:

